-define(datafield_meta,                 <<"meta">>).
-define(datafield_status,               <<"status">>).
-define(datafield_code,                 <<"code">>).
-define(datafield_slogan,               <<"slogan">>).

-define(datafield_imdb_id,              <<"imdbId">>).
-define(datafield_movie_title,          <<"movieTitle">>).
-define(datafield_available_seats,      <<"availableSeats">>).
-define(datafield_reserved_seats,       <<"reservedSeats">>).
-define(datafield_reservation_id,       <<"reservationId">>).
-define(datafield_screen_id,            <<"screenId">>).
